config/routes.rb
require 'sidekiq/web' unless Rails.env == "production"

Myflix::Application.routes.draw do
  get '/home', controller: 'videos', action: 'index'
  get '/sign_in', to: 'sessions#new'
  post '/sign_in', to: 'sessions#create', as: nil
  get '/sign_out', to: 'sessions#destroy'
  
  get '/register', to: 'users#new', as: 'register_user'
  resources 'users', only: [:create, :show]
  get '/register/:token', to: "users#new_with_invitation_token", as: 'register_with_token'

  namespace :admin do
    resources :videos, only: [:new, :create]
    resources :payments, only: [:index]
  end

  get '/people', to: 'relationships#index'
  resources 'relationships', only: [:create, :destroy]

  resources 'categories', only: [:show]
  resources 'videos', only: [:show] do 
    collection do
      post 'search', to: 'videos#search'
    end

    resources 'reviews', only: [:create]
  end

  get 'forgot_password', to: "forgot_passwords#new"
  get 'forgot_password_confirmation', to: "forgot_passwords#confirm"
  resources 'forgot_passwords', only: [:create]

  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: "pages#expired_token"

  resources 'invitations', only: [:new, :create]

  resources 'queue_items', only: [:index, :create, :destroy], path: 'my_queue'
  post 'update_queue', to: 'queue_items#update_queue'

  resources 'plans', only: [:index, :create], path: "billing"
  #post 'update_plans', to: 'plans#create'
  delete 'plans', to: 'plans#destroy', path: "billing"

  root to: 'pages#front'
  get 'ui(/:action)', controller: 'ui'

  #get 'stripe_events', to: "stripe_events/webhook#index"
  #post 'stripe_events', to: "stripe_events/webhook#receive"

  mount Sidekiq::Web, at: "/sidekiq" unless Rails.env == "production"
  mount StripeEvent::Engine => '/stripe_events'
end

app/controllers/forgot_passwords_controller.rb
class ForgotPasswordsController < ApplicationController
  def create
    @user = User.where(email: params[:email]).first
    if @user
      AppMailersWorker.perform_async(@user.id, @user.class.to_s, :send_forgot_password)
      redirect_to forgot_password_confirmation_path
    else
      flash[:error] = params[:email].blank? ? "Email cannot be blank." : "Email input does not exist in system."
      redirect_to forgot_password_path
    end
  end
end

app/views/forgot_passwords/confirm.html.haml
%section.confirm_password_reset.container
  .row
    .span10.offset1
      %p We have send an email with instruction to reset your password.

app/views/forgot_passwords/new.html.haml
%section.forgot_password.container
  .row
    .span10.offset1
      = form_tag forgot_passwords_path, class: "sign_in", method: :post do 
        %header
          %h1 Forgot Password?
          %p We will send you an email with a link that you can use to reset your password.
        %fieldset
          = label_tag :email, "Email Address"
          = text_field_tag :email
        %fieldset.action
          %input(type="submit" value="Send Email" class="btn")