config/routes.rb
require 'sidekiq/web' unless Rails.env == "production"

Myflix::Application.routes.draw do
  get '/home', controller: 'videos', action: 'index'
  get '/sign_in', to: 'sessions#new'
  post '/sign_in', to: 'sessions#create', as: nil
  get '/sign_out', to: 'sessions#destroy'
  
  get '/register', to: 'users#new', as: 'register_user'
  resources 'users', only: [:create, :show]
  get '/register/:token', to: "users#new_with_invitation_token", as: 'register_with_token'

  namespace :admin do
    resources :videos, only: [:new, :create]
    resources :payments, only: [:index]
  end

  get '/people', to: 'relationships#index'
  resources 'relationships', only: [:create, :destroy]

  resources 'categories', only: [:show]
  resources 'videos', only: [:show] do 
    collection do
      post 'search', to: 'videos#search'
    end

    resources 'reviews', only: [:create]
  end

  get 'forgot_password', to: "forgot_passwords#new"
  get 'forgot_password_confirmation', to: "forgot_passwords#confirm"
  resources 'forgot_passwords', only: [:create]

  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: "pages#expired_token"

  resources 'invitations', only: [:new, :create]

  resources 'queue_items', only: [:index, :create, :destroy], path: 'my_queue'
  post 'update_queue', to: 'queue_items#update_queue'

  resources 'plans', only: [:index, :create], path: "billing"
  #post 'update_plans', to: 'plans#create'
  delete 'plans', to: 'plans#destroy', path: "billing"

  root to: 'pages#front'
  get 'ui(/:action)', controller: 'ui'

  #get 'stripe_events', to: "stripe_events/webhook#index"
  #post 'stripe_events', to: "stripe_events/webhook#receive"

  mount Sidekiq::Web, at: "/sidekiq" unless Rails.env == "production"
  mount StripeEvent::Engine => '/stripe_events'
end

app/models/user.rb
class User < ActiveRecord::Base 
  has_many :reviews, -> { order("created_at DESC") }
  has_many :queue_items, -> { order("position ASC") }
  has_many :following_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :leading_relationships, class_name: "Relationship", foreign_key: :leader_id

  has_secure_password validations: false
  
  validates :password, on: :create, length: {minimum: 9}
  validates_presence_of :full_name, :email, :password
  validates_uniqueness_of :email

  include Tokenable

  def normalize_queue_items_position
    reload.queue_items.sort_by!(&:position).each_with_index do |item, index|
      item.update_attributes(position: index + 1)
    end
  end

  def queued_video?(video)
    queue_items.find_by(video_id: video.id)
  end

  def follow(another_user) 
    self.following_relationships.create(leader: another_user) if self.can_follows?(another_user) && another_user != nil
  end

  def follows?(another_user = nil) 
    following_relationships.map(&:leader).include?(another_user)
  end

  def can_follows?(another_user)
    !(self.follows?(another_user) || self == another_user)
  end
  
  def deactivate!
    update_column(:active, false)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, :require_activation, only: [:show]

  def new
    @user = User.new
    render 'new'
  end

  def create
    @user = User.new(create_user)
    result = UserSignup.new(@user).sign_up(params[:stripeToken], params[:invitation_token])

    if result.successful?
      flash[:success] = result.status_message
      redirect_to root_path
    else
      flash.now[:error] = result.status_message
      render :new
    end
  end

  def show
    @user = User.find params[:id]
  end

  def new_with_invitation_token
    invitation = Invitation.where(token: params[:token]).first
    if invitation
      @user = User.new(email: invitation.recipient_email)
      @invitation_token = invitation.token
      render :new
    else
      redirect_to expired_token_path
    end
  end

  private

  def create_user
    params.require(:user).permit(:full_name, :password, :email, :password_confirmation)
  end
end

app/views/users/_errors.html.haml
-if object.errors.any?
  .row
    .alert.alert-error.span8
      %a.close(data-dismiss='alert') &#215;
      %h5 Please fix the following errors:

app/views/users/new.html.haml
- content_for :head do
  = javascript_include_tag 'register'

<script type="text/javascript" src="https://js.stripe.com/v2/"></script>

<script type="text/javascript">
Stripe.setPublishableKey("#{ENV['STRIPE_PUBLISHABLE_KEY']}");
</script>

%section.register.container
  .row
    .span10.offset1
      =simple_payment_form @user do |f|
        %header
          %h1 Register
          = render 'errors', object: @user
          %fieldset
            - group = @user.errors.include?(:email) ? "control-group error" : "control-group"
            %div(class=group)
              %label.control-label(for="user_email") Email Address
              .controls
                .input-prepend
                  %span.add-on
                    %i.icon-envelope
                  =f.input_field :email, class: "span3", placeholder: "ex: email@example.com"
                - if @user.errors.include?(:email)
                  %span.help-inline 
                    =@user.errors.full_messages_for(:email).first
            - group = @user.errors.include?(:full_name) ? "control-group error" : "control-group"
            %div(class=group)
              %label.control-label(for="full_name") Full Name
              .controls
                .input-prepend
                  %span.add-on 
                    %i.icon-user
                  =f.input_field :full_name, class: "span3", placeholder: "ex: David Bowie"
                - if @user.errors.include?(:full_name)
                  %span.help-inline 
                    =@user.errors.full_messages_for(:full_name).first
            - group = @user.errors.include?(:password) ? "control-group error" : "control-group"
            %div(class=group)
              %label.control-label(for="user_password") Password
              .controls
                .input-prepend
                  %span.add-on 
                    %i.icon-certificate
                  =f.input_field :password, class: "span3", placeholder: "do not less than 9 characters."
                - if @user.errors.include?(:password)
                  %span.help-inline 
                    =@user.errors.full_messages_for(:password).first
            - group = @user.errors.include?(:password_confirmation) ? "control-group error" : "control-group info"
            %div(class=group)
              %label.control-label(for="user_password_confirmation") Confirm Password 
              .controls
                .input-prepend
                  %span.add-on 
                    %i.icon-ok-sign
                  =f.input_field :password_confirmation, class: "span3", placeholder: "Enter the password again."
                - if @user.errors.include?(:password_confirmation)
                  %span.help-inline 
                    =@user.errors.full_messages_for(:password_confirmation).first
            = hidden_field_tag :invitation_token, @invitation_token
          %fieldset.credit_card
            %span.payment-errors
            .control-group
              %label.control-label(for="credit-card-number") Credit Card Number
              .controls
                %input.span3(type="text" data-stripe="number" id="credit-card-number")
            .control-group
              %label.control-label(for="security-code") Security Code
              .controls
                %input.span3(type="text" data-stripe="cvc" id="security-code")
            .control-group
              %label.control-label Expiration
              .controls
                = select_month(Date.today, {add_month_numbers: true}, class: 'span2', data: {stripe: "exp-month"})
                = select_year(Date.today.year, {start_year: Date.today.year, end_year: Date.today.year + 4}, :"data-stripe" => "exp-year", class: 'span1')
          %fieldset.actions.control-group
            .controls
              %input(type="submit" value="Sign Up" class="btn")
              = link_to "Forgot Password?", forgot_password_path 

app/views/users/show.html.haml
%section.user.container
  .row
    .span10.offset1
      %article
        %header
          %img(src="http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(@user.email.downcase)}?s=40")
          %h2 #{@user.full_name}'s video collections (#{@user.queue_items.count})
          = link_to "Follow", relationships_path(leader_id: @user.id), class: 'btn', method: "post" if current_user.can_follows?(@user)
        %table.table
          %thead
            %tr
              %th(width="30%") Video Title
              %th(width="15%") Genre
          %tbody
            - @user.queue_items.each do |item|
              %tr
                %td
                  = link_to item.video.title, item.video
                %td
                  = link_to item.category_name,  item.category

%section.user_reviews.container
  .row
    .span10.offset1
      %header
        %h3 #{@user.full_name}'s Reviews (#{@user.reviews.count})
      %ul
        - @user.reviews.each do |r|
          - if r.video
            %article.review
              %li.row
                .span2
                  %p
                    = link_to r.video.title, r.video
                  %span 
                    = r.rating ? "Rating: #{r.rating} / 5" : "Rating: N/A" 
                .span8
                  %p
                    = r.content