config/routes.rb
require 'sidekiq/web' unless Rails.env == "production"

Myflix::Application.routes.draw do
  get '/home', controller: 'videos', action: 'index'
  get '/sign_in', to: 'sessions#new'
  post '/sign_in', to: 'sessions#create', as: nil
  get '/sign_out', to: 'sessions#destroy'
  
  get '/register', to: 'users#new', as: 'register_user'
  resources 'users', only: [:create, :show]
  get '/register/:token', to: "users#new_with_invitation_token", as: 'register_with_token'

  namespace :admin do
    resources :videos, only: [:new, :create]
    resources :payments, only: [:index]
  end

  get '/people', to: 'relationships#index'
  resources 'relationships', only: [:create, :destroy]

  resources 'categories', only: [:show]
  resources 'videos', only: [:show] do 
    collection do
      post 'search', to: 'videos#search'
    end

    resources 'reviews', only: [:create]
  end

  get 'forgot_password', to: "forgot_passwords#new"
  get 'forgot_password_confirmation', to: "forgot_passwords#confirm"
  resources 'forgot_passwords', only: [:create]

  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: "pages#expired_token"

  resources 'invitations', only: [:new, :create]

  resources 'queue_items', only: [:index, :create, :destroy], path: 'my_queue'
  post 'update_queue', to: 'queue_items#update_queue'

  resources 'plans', only: [:index, :create], path: "billing"
  #post 'update_plans', to: 'plans#create'
  delete 'plans', to: 'plans#destroy', path: "billing"

  root to: 'pages#front'
  get 'ui(/:action)', controller: 'ui'

  #get 'stripe_events', to: "stripe_events/webhook#index"
  #post 'stripe_events', to: "stripe_events/webhook#receive"

  mount Sidekiq::Web, at: "/sidekiq" unless Rails.env == "production"
  mount StripeEvent::Engine => '/stripe_events'
end

app/models/video.rb
class Video < ActiveRecord::Base 
  has_many :reviews, -> { order("created_at DESC") }
  belongs_to :category, touch: true
  validates_presence_of :title, :description

  #delegate :name, to: :category

  mount_uploader :large_cover, LargeCoverUploader
  mount_uploader :small_cover, SmallCoverUploader

  def self.search_by_title(str)
    if str.blank? || str.match(/[%|_|!]/)
      []
    else
      # Postgre SQL syntax
      self.where(["LOWER(title) LIKE LOWER(?)", "%#{str}%"]).order("created_at DESC")
    end
  end

  def self.search_by_title_categorized(search_term)
    videos = search_by_title(search_term)
    result = videos.reduce(SearchResult.new) do |result, video|
              result.add_videos(video)
              result
            end
    result.data
  end

  def reviews_total_rate
    total_rate = 0.00
    count = 0
    total_rate = reviews.reduce(total_rate) do |sum, c| 
      if c == nil || c.rating == nil
        sum
      else
        count += 1
        sum += c.rating
      end
    end
    if count != 0
      total_rate /= count 
      total_rate.round(1)
    end
  end

end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < AdminsController 
  before_action :require_user

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(create_video)
    if @video.save
      expire_fragment ["videos_category", "#{@video.category_id}"]
      flash[:success] = "You have successfully added the new video #{@video.title}."
      redirect_to new_admin_video_path
    else
      flash[:error] = "You are failed to add the video, please try again."
      render :new
    end
  end

  private

  def create_video
    params.require(:video).permit!
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :require_user, :require_activation, except: [:front]

  def index
    @videos = Video.all
    @categories = Category.all
  end

  def show
    @video = VideoDecorator.decorate(Video.find params[:id])
    render 'video_show'
  end

  def search
    @items = Video.search_by_title_categorized(params[:search])
  end
end

app/views/videos/_feed_back.html.haml
:plain 
  <script type="text/javascript" src="//assets.zendesk.com/external/zenbox/v2.6/zenbox.js"></script>
  <style type="text/css" media="screen, projection">
    @import url(//assets.zendesk.com/external/zenbox/v2.6/zenbox.css);
    #zenbox_tab {
      top: 20%;
      border-color: #b9090b;
    }
  </style>
  <script type="text/javascript">
    if (typeof(Zenbox) !== "undefined") {
      Zenbox.init({
        dropboxID:   "20116929",
        url:         "https://z3n372.zendesk.com",
        tabTooltip:  "Support",
        tabImageURL: "https://p4.zdassets.com/external/zenbox/images/tab_support_right.png",
        tabColor:    "#b9090b",
        tabPosition: "Right"
      });
    }
  </script>

app/views/videos/_search_list.html.haml
%article.video_category
  %header
    %h3= link_to link_name
  .videos.row
    - videos.each do |v|
      .video.span2
        = link_to video_path(v), nil do
          %img(src="#{v.small_cover_url}")

app/views/videos/index.html.haml
- @categories.each do |category|
  - cache ["videos_category", "#{category.id}"] do
    %article.video_category
      %header
        %h3= link_to "#{category.name}"
      .videos.row
        - category.recent_videos.each do |video|
          .video.span2
            = link_to video_path(video), nil do
              %img(src="#{video.small_cover_url}")

app/views/videos/search.html.haml
- @items.each do |c, v|
  - if c == "Uncategoried"
    = render 'search_list', videos: v, link_name: "Uncategoried"
  - else
    = render 'search_list', videos: v, link_name: "#{c.name}"

app/views/videos/video_show.html.haml
%article.video
  .container
    .row
      .video_large_cover.span7.offset1
        %img(src="#{@video.large_cover_url}")
      .video_info.span3
        %header
          %h3 #{@video.title}
          %span 
            = "#{@video.rating}"
        %p #{@video.description}
        .actions
          %a.btn.btn-primary(href="#{@video.video_url}") Watch Now
          = (link_to "+ My Queue", queue_items_path(video_id: @video.id), method: :post, class: 'btn') unless current_user.queued_video?(@video)

%section.reviews.container
  .row
    .span10.offset1
      = form_for [@video, Review.new] do |f|
        %fieldset
          = f.label :rating, "Rate this video"
          .select_grouping
            = f.select :rating, options_for_video_reviews
          = f.label :content, "Write Review"
          = f.text_area :content, rows: 6, class: "span6"
        %fieldset.actions.clearfix
          = f.submit "Submit", class: "btn", style: "font-family: 'Bree Serif', serif"
          = link_to "Cancel", @video
      %header
        %h3 
          = "User Reviews (#{@video.reviews.size})"
      %ul
        - @video.reviews.each do |r|
          %article.review
            %li.row
              .span2
                %span 
                  = r.rating ? "Rating: #{r.rating} / 5" : "Rating: N/A" 
                %p 
                  by 
                  %a(href="") 
                    = link_to r.user.full_name, r.user
                  %br
                  = "at #{r.created_at.strftime("%m/%d/%Y %H:%M:%S")}"
              .span8
                %p 
                  = r.content