config/routes.rb
require 'sidekiq/web' unless Rails.env == "production"

Myflix::Application.routes.draw do
  get '/home', controller: 'videos', action: 'index'
  get '/sign_in', to: 'sessions#new'
  post '/sign_in', to: 'sessions#create', as: nil
  get '/sign_out', to: 'sessions#destroy'
  
  get '/register', to: 'users#new', as: 'register_user'
  resources 'users', only: [:create, :show]
  get '/register/:token', to: "users#new_with_invitation_token", as: 'register_with_token'

  namespace :admin do
    resources :videos, only: [:new, :create]
    resources :payments, only: [:index]
  end

  get '/people', to: 'relationships#index'
  resources 'relationships', only: [:create, :destroy]

  resources 'categories', only: [:show]
  resources 'videos', only: [:show] do 
    collection do
      post 'search', to: 'videos#search'
    end

    resources 'reviews', only: [:create]
  end

  get 'forgot_password', to: "forgot_passwords#new"
  get 'forgot_password_confirmation', to: "forgot_passwords#confirm"
  resources 'forgot_passwords', only: [:create]

  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: "pages#expired_token"

  resources 'invitations', only: [:new, :create]

  resources 'queue_items', only: [:index, :create, :destroy], path: 'my_queue'
  post 'update_queue', to: 'queue_items#update_queue'

  resources 'plans', only: [:index, :create], path: "billing"
  #post 'update_plans', to: 'plans#create'
  delete 'plans', to: 'plans#destroy', path: "billing"

  root to: 'pages#front'
  get 'ui(/:action)', controller: 'ui'

  #get 'stripe_events', to: "stripe_events/webhook#index"
  #post 'stripe_events', to: "stripe_events/webhook#receive"

  mount Sidekiq::Web, at: "/sidekiq" unless Rails.env == "production"
  mount StripeEvent::Engine => '/stripe_events'
end

app/views/shared/_header.html.haml
%section#top-header.row
  %h1.span2
    = link_to "MyFLiX", (logged_in? ? home_path : sign_in_path)
  - if logged_in?
    %ul.span4.clearfix
      %li= link_to "Videos", home_path
      %li= link_to "My Queue", queue_items_path
      %li= link_to "People", people_path
    =form_tag search_videos_path, class: "span5 for-search" do 
      =search_field_tag('search', params[:search] || '', class: 'search-query', placeholder: "Search for videos here")
      %button.btn(type="submit") Search
    #user_links.pull-right
      %ul
        %li.dropdown
          %a(href="#" id="dlabel" role="button" data-toggle="dropdown" class="dropdown-toggle" data-target="#")
            = "Welcome, #{current_user.full_name}"
            %b.caret
          %ul.dropdown-menu(role="menu" aria-labelledby="dlabel")
            %li
              =link_to "Account", home_path
              %a(href="/billing") Plan and Billing
              = link_to "Invite a Friend", new_invitation_path
              = link_to "Sign Out", (logged_in? ? sign_out_path : root_path)

app/views/shared/_messages.html.haml
- unless response.cache_control[:public]
  - flash.each do |name, msg|
    %div(class="alert alert-#{name}")
      %a.close(data-dismiss='alert') &#215;
      = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)